### ISSUE TITLE
If Verbosity is verbose, output should include the command line of a tool that is being run

### ISSUE THREAD

**Issue by ferventcoder** [cake-contrib/Cake.Eazfuscator.Net#7]
I realize this is maybe not the place to put this as it defers to the Run method somewhere inside Cake, but I haven't dug in far enough. It's possible newer versions of cake do this already, but knowing what is being run is helpful, especially when attempting to debug what is going wrong.

**Comment by gep13** [comment]
If you run the Cake script with Diagnostic verbosity, then the command that is being executed will be shown.

Or, there is an environment variable that you can set which has the same effect:

https://github.com/cake-build/cake/pull/2486

**Comment by ferventcoder** [comment]
Grats. Ignore me.
